FROM ubuntu

MAINTAINER Daniel Cardoza <danielpcardoza@gmail.com>

RUN apt-get -y update
RUN apt-get -y install vim

RUN echo 'module(load="imudp")' >> /etc/rsyslog.conf
RUN echo 'input(type="imudp" port="1337")' >> /etc/rsyslog.conf
RUN echo 'module(load="imtcp")' >> /etc/rsyslog.conf
RUN echo 'input(type="imtcp" port="1338")' >> /etc/rsyslog.conf

ENTRYPOINT ["/usr/sbin/rsyslogd"]
CMD ["-n"]
